### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by Abdulgafar4** [shanmugharajk/react-point-of-sale#12]
Please, it will be good if you explain how to go with nodemon and how to run it

**Comment by fasihshaikh** [comment]
username and password not working

**Comment by shanmugharajk** [comment]
@fasihshaikh  what username and password have you tried?

```
username: admin
password: admin
```

should work. I tested right now.

Make sure that you run both web and api both the project.

```
npm run dev:web

npm run dev:api
```

separately in the root of the project.

**Comment by shanmugharajk** [comment]
@Abdulgafar4  the nodemon setup is done. Just run `npm run dev:api` it would run automatically in watch mode and get re compiled on change.

The nodemon.json file has the settings in it

```
{
  "watch": ["src"],
  "ext": "ts",
  "ignore": ["src/**/*.spec.ts"],
  "exec": "ts-node ./src/index.ts"
}
```

as you can see `ts-node` is used to run typescript code.

**Comment by shanmugharajk** [comment]
@fasihshaikh I deleted the comment you left on the readme file since its already asked here.

**Comment by adielfera** [comment]
do you know what do I miss here?
![image](https://user-images.githubusercontent.com/77710537/106546348-03d67800-64d9-11eb-9634-fe99854513cc.png)
