### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Abdulgafar4** [shanmugharajk/react-point-of-sale#13]
Please When Will These Finish

**Comment by shanmugharajk** [comment]
Unfortunately I'm not getting much time these days. Cannot say an exact timeline. Please ask only issues related to this project in issues category.

**Comment by shanmugharajk** [comment]
I will resume this work by next week. Planning to use NestJs for api's and same ReactJs, React Query, Material UI for frontend with latest version.
