### ISSUE TITLE
Unable to use yarn dev:api

### ISSUE THREAD

**Issue by adielfera** [shanmugharajk/react-point-of-sale#14]
Kindly advice what do I missed? Thank you

![image](https://user-images.githubusercontent.com/77710537/106546428-2f596280-64d9-11eb-8c12-dcadb85df667.png)

**Comment by clundy-columbia** [comment]
try
yarn dev:web from the root directory

**Comment by adielfera** [comment]
yarn dev:web is ok. the other command to connect to db does not work. yarn dev:api

**Comment by shanmugharajk** [comment]
@adielfera Please share the node & npm versions you are on and also the exact steps you followed.

**Comment by adielfera** [comment]
@shanmugharajk , here is my version

![image](https://user-images.githubusercontent.com/77710537/106935606-90578500-66e9-11eb-938a-a6a1bda14c4c.png)

**Comment by adielfera** [comment]
I followed the following step
![image](https://user-images.githubusercontent.com/77710537/106936024-12e04480-66ea-11eb-81b2-b0d0c0ba9ea4.png)

**Comment by riyazar2001** [comment]
Hello 

any body there to solve the issue with the DB

Thanks

**Comment by shanmugharajk** [comment]
@adielfera , 

I tried with `v12.14.1` node version. It's working fine for me. I guess some of the packages are not compatible. So for now please try with `v12.14.1` and navigate to the folder `api` and delete the `yarn.lock` file. Then try installing the npm packages and give it a shot to run the server.

I will upgrade this project with all dependencies to make it work with the latest node as soon as I can.

**Comment by shanmugharajk** [comment]
@riyazar2001 please explain what's the issue with DB?.

The username and password to login this app is `admin` and `admin`

**Comment by riyazar2001** [comment]
Do you have any video explanations about this project in youtube ? when i
clone the project from github its not logging and an its net able to get
complete the 'npm run dev:api'
 the error in the code seems like this
[image: image.png]

**Comment by riyazar2001** [comment]
This is the compiling error

[image: image.png]

**Comment by shanmugharajk** [comment]
I will try to link a video, but I'm not sure it will help you. Because anyways in my machine its working and I shared my node version which I use already. Since this is more related to environment please try in StackOverflow.

**Comment by adielfera** [comment]
I try change the version but still hit the same error
![image](https://user-images.githubusercontent.com/77710537/108153035-5783bc80-70a8-11eb-837d-efaf84d74293.png)
