### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by shabir67** [shanmugharajk/react-point-of-sale#16]
<img width="607" alt="Screen Shot 2021-02-17 at 20 59 36" src="https://user-images.githubusercontent.com/39258245/108214778-27e5ba80-7163-11eb-8c73-710954834422.png">
<img width="461" alt="Screen Shot 2021-02-17 at 21 01 34" src="https://user-images.githubusercontent.com/39258245/108215166-9a569a80-7163-11eb-84f3-090c669586d1.png">

It says a message like this, is there any problem? especially when installing the package?

**Comment by shanmugharajk** [comment]
Please start the api server. Thats what the message says.
